# Generated by Django 5.0.7 on 2024-08-01 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='createdat',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='updatedat',
            new_name='updated_at',
        ),
    ]
